[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.23"

remappings = [
  "account-abstraction/=lib/account-abstraction/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
